version: 0.2

phases:
  build:
    commands:
      - name: Login to Amazon ECR
        command: aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 148761652675.dkr.ecr.ap-southeast-2.amazonaws.com
        

      - name: Build Docker image
        command: docker build -t test-node-app .

      - name: Tag Docker image
        command: docker tag test-node-app:latest 148761652675.dkr.ecr.ap-southeast-2.amazonaws.com/test-node-app:latest

      - name: Push Docker image to ECR
        command: docker push 148761652675.dkr.ecr.ap-southeast-2.amazonaws.com/test-node-app:latest


